minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: password123
  bucket:
    raw: raw-uploads
    public: public-streams

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093
    consumer:
      group-id: transcoding-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
